/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        paper: 'var(--paper)',
        ink: 'var(--ink)',
        'ink-80': 'var(--ink-80)',
        'ink-60': 'var(--ink-60)',
        'ink-40': 'var(--ink-40)',
        'ink-20': 'var(--ink-20)',
        'ink-10': 'var(--ink-10)',
        signal: 'var(--signal)',
        ok: 'var(--ok)',
        warn: 'var(--warn)',
        error: 'var(--error)',
      },
      fontFamily: {
        display: 'var(--font-display)',
        editorial: 'var(--font-editorial)',
      },
      fontSize: {
        'display-xl': ['96px', { lineHeight: '0.95', letterSpacing: '-3%' }],
        'display-lg': ['72px', { lineHeight: '0.95', letterSpacing: '-3%' }],
        'display-md': ['56px', { lineHeight: '1.0', letterSpacing: '-2%' }],
        'display-sm': ['40px', { lineHeight: '1.05', letterSpacing: '-2%' }],
        'heading-lg': ['32px', { lineHeight: '1.1', letterSpacing: '-1%' }],
        'heading-md': ['24px', { lineHeight: '1.2', letterSpacing: '-1%' }],
        'heading-sm': ['18px', { lineHeight: '1.3', letterSpacing: '0%' }],
        'body-lg': ['18px', { lineHeight: '1.55', letterSpacing: '0%' }],
        body: ['16px', { lineHeight: '1.55', letterSpacing: '0%' }],
        'body-sm': ['14px', { lineHeight: '1.5', letterSpacing: '0%' }],
        'mono-lg': ['16px', { lineHeight: '1.4', letterSpacing: '5%' }],
        mono: ['13px', { lineHeight: '1.4', letterSpacing: '8%' }],
        'mono-sm': ['11px', { lineHeight: '1.4', letterSpacing: '10%' }],
      },
      fontWeight: {
        400: '400',
        500: '500',
      },
      borderRadius: {
        sm: '2px',
        DEFAULT: '2px',
        md: '4px',
        full: '999px',
      },
      spacing: {
        0: '0',
        1: '4px',
        1.5: '6px',
        2: '8px',
        3: '12px',
        4: '16px',
        6: '24px',
        8: '32px',
        12: '48px',
        16: '64px',
        24: '96px',
        32: '128px',
        48: '192px',
      },
      borderWidth: {
        DEFAULT: '1px',
        2: '2px',
      },
      boxShadow: {
        panel: '0 1px 0 var(--ink-20), 0 24px 48px -12px rgba(10,10,10,0.12)',
      },
      transitionDuration: {
        120: '120ms',
        240: '240ms',
        300: '300ms',
        400: '400ms',
        500: '500ms',
        600: '600ms',
        720: '720ms',
      },
      transitionTimingFunction: {
        out: 'cubic-bezier(0.16, 1, 0.3, 1)',
        'out-expo': 'cubic-bezier(0.16, 1, 0.3, 1)',
        'in-out': 'cubic-bezier(0.42, 0, 0.58, 1)',
      },
    },
  },
  plugins: [],
};
